apiVersion: apps/v1
kind: Deployment
metadata:
  name: MSSQLLocalDB
spec:
  replicas: 1
  selector:
    matchLabels:
      app: MSSQLLocalDB
  template:
    metadata:
      labels:
        app: MSSQLLocalDB
    spec:
      terminationGracePeriodSeconds: 30
      hostname: mssqlinst
      securityContext:
        fsGroup: 10001
      containers:
        - name: MSSQLLocalDB
          image: mcr.microsoft.com/mssql/server:2019-latest
          ports:
            - containerPort: 1433
          env:
            - name: MSSQL_PID
              value: "Developer"
            - name: ACCEPT_EULA
              value: "Y"
            - name: SA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mssql
                  key: SA_PASSWORD
