apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment1
spec:
  selector:
    matchLabels:
      app: myapp1
  replicas: 2
  template:
    metadata:
      labels:
        app: myapp1
    spec:
      containers:
      - name: myapp1
        image: sumithpe/gadgets:latest
        ports:
        - containerPort: 80
