apiVersion: apps/v1
kind: Deployment
metadata:
  name: service
spec:
  selector:
    matchLabels:
      app: service
  replicas: 2
  template:
    metadata:
      labels:
        app: service
    spec:
      containers:
        - name: poc6sercon
          image: sumithpe/poc6ser:latest
          ports:
            - containerPort: 80
