apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentication
spec:
  selector:
    matchLabels:
      app: authentication
  replicas: 2
  template:
    metadata:
      labels:
        app: authentication
    spec:
      containers:
        - name: poc6authcon
          image: sumithpe/poc6auth:latest
          ports:
            - containerPort: 80
