apiVersion: apps/v1
kind: Deployment
metadata:
  name: mssqldatabase
spec:
  selector:
    matchLabels:
      app: mssqldatabase
  replicas: 2
  template:
    metadata:
      labels:
        app: mssqldatabase
    spec:
      containers:
        - name: MSSQLLocalDB
          image: mcr.microsoft.com/mssql/server:2022-latest
          env:
            - name: MSSQL_PID
              value: "Developer"
            - name: ACCEPT_EULA
              value: "Y"
            - name: MSSQL_SA_PASSWORD
              value: "Sumit@mssql8796"
          ports:
            - containerPort: 1433
