apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentication
spec:
  selector:
    matchLabels:
      app: authentication
  replicas: 2
  template:
    metadata:
      labels:
        app: authentication
    spec:
      containers:
        - name: poc6authcon
          image: sumithpe/poc6auth:latest
          resources:
            requests:
              memory: "2G"
              cpu: "2000m"
            limits:
              memory: "2G"
              cpu: "2000m"
          ports:
            - containerPort: 80
